// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PPMAPI.DataAccess;

#nullable disable

namespace PPMAPI.Migrations
{
    [DbContext(typeof(PPMDbContext))]
    partial class PPMDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PPMModelLibrary.Models.Properties.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal");

                    b.Property<float>("Size")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("PPMModelLibrary.Models.Properties.RentableProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal");

                    b.Property<decimal?>("RentalFee")
                        .HasColumnType("decimal");

                    b.Property<float>("Size")
                        .HasColumnType("real");

                    b.Property<string>("TenantUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("TenantUserId");

                    b.ToTable("RentableProperties");
                });

            modelBuilder.Entity("PPMModelLibrary.Models.Transactions.Cost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RentablePropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("RentablePropertyId");

                    b.ToTable("Costs");
                });

            modelBuilder.Entity("PPMModelLibrary.Models.Transactions.Revenue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RentablePropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("RentablePropertyId");

                    b.ToTable("Revenues");
                });

            modelBuilder.Entity("PPMModelLibrary.Models.Users.Owner", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("PPMModelLibrary.Models.Users.Tenant", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("PPMModelLibrary.Models.UtilityModels.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("PPMModelLibrary.Models.ValueModifiers.ValueDecrease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RentablePropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("RentablePropertyId");

                    b.ToTable("ValueDecreases");
                });

            modelBuilder.Entity("PPMModelLibrary.Models.ValueModifiers.ValueIncrease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RentablePropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("RentablePropertyId");

                    b.ToTable("ValueIncreases");
                });

            modelBuilder.Entity("PPMModelLibrary.Models.Properties.Property", b =>
                {
                    b.HasOne("PPMModelLibrary.Models.UtilityModels.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPMModelLibrary.Models.Users.Owner", "Owner")
                        .WithMany("Properties")
                        .HasForeignKey("OwnerUserId");

                    b.Navigation("Address");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PPMModelLibrary.Models.Properties.RentableProperty", b =>
                {
                    b.HasOne("PPMModelLibrary.Models.UtilityModels.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPMModelLibrary.Models.Users.Owner", "Owner")
                        .WithMany("Rentableproperties")
                        .HasForeignKey("OwnerUserId");

                    b.HasOne("PPMModelLibrary.Models.Users.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantUserId");

                    b.Navigation("Address");

                    b.Navigation("Owner");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PPMModelLibrary.Models.Transactions.Cost", b =>
                {
                    b.HasOne("PPMModelLibrary.Models.Properties.Property", "Property")
                        .WithMany("Costs")
                        .HasForeignKey("PropertyId");

                    b.HasOne("PPMModelLibrary.Models.Properties.RentableProperty", "RentableProperty")
                        .WithMany("Costs")
                        .HasForeignKey("RentablePropertyId");

                    b.Navigation("Property");

                    b.Navigation("RentableProperty");
                });

            modelBuilder.Entity("PPMModelLibrary.Models.Transactions.Revenue", b =>
                {
                    b.HasOne("PPMModelLibrary.Models.Properties.Property", "Property")
                        .WithMany("Revenues")
                        .HasForeignKey("PropertyId");

                    b.HasOne("PPMModelLibrary.Models.Properties.RentableProperty", "RentableProperty")
                        .WithMany("Revenues")
                        .HasForeignKey("RentablePropertyId");

                    b.Navigation("Property");

                    b.Navigation("RentableProperty");
                });

            modelBuilder.Entity("PPMModelLibrary.Models.ValueModifiers.ValueDecrease", b =>
                {
                    b.HasOne("PPMModelLibrary.Models.Properties.Property", "Property")
                        .WithMany("ValueDecreases")
                        .HasForeignKey("PropertyId");

                    b.HasOne("PPMModelLibrary.Models.Properties.RentableProperty", "RentableProperty")
                        .WithMany("ValueDecreases")
                        .HasForeignKey("RentablePropertyId");

                    b.Navigation("Property");

                    b.Navigation("RentableProperty");
                });

            modelBuilder.Entity("PPMModelLibrary.Models.ValueModifiers.ValueIncrease", b =>
                {
                    b.HasOne("PPMModelLibrary.Models.Properties.Property", "Property")
                        .WithMany("ValueIncreases")
                        .HasForeignKey("PropertyId");

                    b.HasOne("PPMModelLibrary.Models.Properties.RentableProperty", "RentableProperty")
                        .WithMany("ValueIncreases")
                        .HasForeignKey("RentablePropertyId");

                    b.Navigation("Property");

                    b.Navigation("RentableProperty");
                });

            modelBuilder.Entity("PPMModelLibrary.Models.Properties.Property", b =>
                {
                    b.Navigation("Costs");

                    b.Navigation("Revenues");

                    b.Navigation("ValueDecreases");

                    b.Navigation("ValueIncreases");
                });

            modelBuilder.Entity("PPMModelLibrary.Models.Properties.RentableProperty", b =>
                {
                    b.Navigation("Costs");

                    b.Navigation("Revenues");

                    b.Navigation("ValueDecreases");

                    b.Navigation("ValueIncreases");
                });

            modelBuilder.Entity("PPMModelLibrary.Models.Users.Owner", b =>
                {
                    b.Navigation("Properties");

                    b.Navigation("Rentableproperties");
                });
#pragma warning restore 612, 618
        }
    }
}
